#!/bin/bash
#
# mydot - Add aliases and functions to HOME shell
# See https://github.com/hernanmd/mydot
#

set -eo pipefail

install_aliases () {
	# Replace current Bash aliases with mydot's aliases
	# Backup copy of current aliases is in .bash_aliases.bkp
	cp mydot/.bash_aliases ~/.bash_aliases
	# Append system specific aliases
	cat ~/.ss_aliases >> ~/.bash_aliases
	[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases
	printf "Added aliases into ~/.bash_aliases\n"
}

install_functions () {
	cp mydot/.bash_functions ~/.bash_functions
	[[ -f ~/.bash_functions ]] && . ~/.bash_functions
	printf "Added functions into ~/.bash_functions\n"
}

install_bashrc () {
	echo "
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi" >> ~/.bashrc
}

install_aliases
install_functions
install_bashrc
